USE [master]
GO

/****** Object:  Database [DIEMTUYENSINH]    Script Date: 3/23/2023 7:39:05 AM ******/
CREATE DATABASE [DIEMTUYENSINH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DIEMTUYENSINH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEX\MSSQL\DATA\DIEMTUYENSINH.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DIEMTUYENSINH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEX\MSSQL\DATA\DIEMTUYENSINH_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DIEMTUYENSINH] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DIEMTUYENSINH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DIEMTUYENSINH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET ARITHABORT OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DIEMTUYENSINH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DIEMTUYENSINH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DIEMTUYENSINH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DIEMTUYENSINH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DIEMTUYENSINH] SET  MULTI_USER 
GO

ALTER DATABASE [DIEMTUYENSINH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DIEMTUYENSINH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DIEMTUYENSINH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DIEMTUYENSINH] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DIEMTUYENSINH] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DIEMTUYENSINH] SET  READ_WRITE 
GO

